#Minecraft server properties
server-port=25565
motd=Maincraift \u2014 daje roma
max-players=5
allow-cheats=true
view-distance=12
simulation-distance=10
enable-rcon=false
difficulty=hard
gamemode=survival
pvp=true
allow-flight=false
white-list=false
spawn-protection=0
enable-command-block=true
max-tick-time=60000