#Minecraft server properties
server-port=25565
motd=Maincraift \u2014 powered by AWS Spot
max-players=10
view-distance=12
simulation-distance=10
enable-rcon=false
difficulty=normal
gamemode=survival
pvp=true
allow-flight=false
white-list=false
spawn-protection=0
enable-command-block=true
max-tick-time=60000
